"""Se quitaron los campos unicos de de algunas columnas

Revision ID: a285fd67e924
Revises: 
Create Date: 2023-11-19 13:51:36.974298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a285fd67e924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_productDescription_key', type_='unique')
        batch_op.drop_constraint('products_productGender_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('products_productGender_key', ['productGender'])
        batch_op.create_unique_constraint('products_productDescription_key', ['productDescription'])

    # ### end Alembic commands ###
